substitutions:
  # 允许显示的字符集。此列表非常庞大，包含了多语言字符。
  allowed_characters: |-
    厦门室内外弱电书桌未来不会仪表盘屏幕亮度系统设备信号运行地址天气预警无小时分钟下雨大中有渐停后转为开始过就了的又客厅插座音量功耗总电量室外室内·！@#￥%…&*（）—+-=、|【{}】；：'""，《。》/？℃℉￡ abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890~`!$^()_[]\;:'",<.>?

font:
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: extra_icon
    size: 48
    bpp: 4
    glyphs: [
      "\U000F050F", # 温度计
      "\U000F058E", # 湿度百分比
      "\U000F0F30", # 雾霾天气
      "\U000F056E", # 仪表盘
      "\U000F0A1D", # 仪表盘（轮廓）
      "\U000F0335", # 灯泡
      "\U000F0336", # 灯泡（轮廓）
      "\U000F0F54", # 室内温度计
      "\U000F0F55", # 室内温度计（轮廓）
      "\U000F001B", # 空调
      "\U000F0493", # 齿轮
      "\U000F08BB", # 齿轮（轮廓）
      "\U000F0142", # 右箭头
      "\U000F1805", # 荧光灯管（轮廓）
      "\U000F1804", # 荧光灯管
      "\U000F18DE", # 吸顶灯（轮廓）
      "\U000F18DD", # 吸顶灯
      "\U000F0425", # 电源
      "\U000F029A", # 气压表（用于显示 hPa 气压）
      "\U000F05A9", # WiFi
      "\U000F007A", # 电池-10%
      "\U000F007B", # 电池-20%
      "\U000F007C", # 电池-30%
      "\U000F007D", # 电池-40%
      "\U000F007E", # 电池-50%
      "\U000F007F", # 电池-60%
      "\U000F0080", # 电池-70%
      "\U000F0081", # 电池-80%
      "\U000F0082", # 电池-90%
      "\U000F0079", # 电池-100%
      "\U000F089C", # 充电-10%
      "\U000F0086", # 充电-20%
      "\U000F0087", # 充电-30%
      "\U000F0088", # 充电-40%
      "\U000F089D", # 充电-50%
      "\U000F0089", # 充电-60%
      "\U000F089E", # 充电-70%
      "\U000F008A", # 充电-80%
      "\U000F008B", # 充电-90%
      "\U000F0085", # 充电-100%
      "\U000F06A5", # 电源插头（表示无电池，使用 USB-C 供电）
      "\U000F109B", # Home Assistant API
      "\U000F0064", # 助手
      "\U000F0004", # 账户
      "\U000F0156", # 关闭
      "\U000F0415", # 加号
      "\U000F0374", # 减号
      "\U000F00DF", # 亮度调节
      "\U000F03D8", # 调色板
      "\U000F02DC", # 沙发（客厅）
      "\U000F0905", # 电源插座
      "\U000F0E19", # 音量高
      "\U000F09C8", # 功率插头
    ]

  - file: "fonts/materialdesignicons-webfont.ttf"
    id: extra_icon_64
    size: 64
    bpp: 4
    glyphs: [
      "\U000F0D80", # 楼层1
    ]


  # Montserrat 字体（96px，用于时间显示）
  - file: gfonts://Montserrat@600
    id: montserrat_96
    size: 96
    bpp: 4

  # Montserrat 字体（32px，用于数值显示）
  - file: gfonts://Montserrat@600
    id: montserrat_32
    size: 32
    bpp: 4

  # Noto Sans SC 中文字体（32px）
  - file: gfonts://Noto+Sans+SC
    id: noto_sans_sc_32
    size: 32
    bpp: 4
    glyphs: ${allowed_characters}
    ignore_missing_glyphs: true

  # Noto Sans SC 中文字体（48px）
  - file: gfonts://Noto+Sans+SC
    id: noto_sans_sc_48
    size: 48
    bpp: 4
    glyphs: "客厅仪表盘系统设置亮度插座弱电书桌音量功耗总电量室外室内预警地址信号运行"
    ignore_missing_glyphs: true
