# 时间同步配置（Home Assistant + RX8130 实时时钟）
time:
  - platform: homeassistant
    id: ha_time
    on_time_sync:
      then:
        rx8130.write_time:
  - platform: rx8130
    id: rx8130_time
    update_interval: never
    on_time:
      # 就绪后每3秒更新一次
      - seconds: /3
        then:
          - lvgl.label.update:
              id: time_label
              text: !lambda |-
                auto t = id(ha_time).now();
                return t.strftime("%H:%M").c_str();

          - lvgl.label.update:
              id: date_label
              text: !lambda |-
                auto t = id(ha_time).now();
                return t.strftime("%Y-%m-%d %a").c_str();