# ESPHOME 基础配置
esphome:
  name: tab5-ha-hmi-ew
  friendly_name: M5Stack Tab5
  min_version: 2025.12.0

# 日志配置
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG
  logs:
    sensor: INFO
    binary_sensor: INFO

# Home Assistant API 配置
api:
  on_client_connected: 
    then:
      - lvgl.widget.show: api_icon_label
  on_client_disconnected: 
    then:
      - lvgl.widget.hide: api_icon_label

# OTA 远程更新配置
ota:
  platform: esphome

# WiFi 网络配置
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect: 
    then:
      - lvgl.widget.show: wifi_icon_label
  on_disconnect: 
    then:
      - lvgl.widget.hide: wifi_icon_label

packages:
  hardware: !include packages/hardware.yaml
  system: !include packages/system.yaml
  time: !include packages/time.yaml
  fonts: !include packages/fonts.yaml
  sensor: !include packages/sensor.yaml
  button: !include packages/button.yaml
  script: !include packages/script.yaml
  lvgl: !include packages/lvgl.yaml